server:
  port: 8001
  servlet:
    context-path: /onlineEducation/api/v1

spring:
  application:
    name: online-education
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: timesheet_dev
    url: jdbc:mysql://localhost:3306/online_education?serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      pool-name: timesheet-api
      minimum-idle: 2
      maximum-pool-size: 4
      max-lifetime: 180000
      idle-timeout: 170000
  redis:
    host: 120.77.237.202
    port: 6379
    database: 15
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    root: info
    com.wodeer.timesheet.dao: debug

misc:
  enable-output-unknown-exception: true



